Added auto-scaling to eeg graph
luis-wave/wavelit pull request #16
Opened 2024-09-09 16:41 UTC by ppolk-wave

- created a new file to handle eeg graph preprocessing
- updated graphs/eeg_viewer to handle the new auto-scaling
- updated streamlit_dashboards/eeg_visualization to scale the df before creating the plotly figure

2024-09-09 18:19 UTC, luis-wave requested changes

2024-09-09 18:19 UTC, luis-wave commented on dsp/graph_preprocessing.py
> +                      time_constant=0.08,
Where does time constant come into play?

2024-09-09 18:19 UTC, luis-wave commented on dsp/graph_preprocessing.py
> +0.08 sec is roughly equivalent to a 1.9894 Hz cuttoff frequency
Where did you get this info?

2024-09-09 18:19 UTC, luis-wave commented on graphs/eeg_viewer.py
> +                    color="black",
How does this look in dark mode?

2024-09-09 18:19 UTC, luis-wave commented on dsp/graph_preprocessing.py
> +"""
Use MyWaveAnalytics, `filters.eeg_filter(self.mw_object, 1, None)`

2024-09-09 18:19 UTC, luis-wave commented on dsp/graph_preprocessing.py
> +    # bipolar-transverse montage electrodes
from the reference module use `bipolar_transverse_montage`

2024-09-13 02:04 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +# Function that calculates the power spectrum and associated frequencies for a 1d or 2d array of data
this was a placeholder for a function i wanted to write. It has been removed.

2024-09-16 20:52 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +def get_referenced_data(raw_mwa=None, scale_df=False):
I removed all but the necessary scale_dataframe() function necessary for auto-scaling. I will provide these changes in future pull requests with the relevant features

2024-09-16 20:54 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +0.08 sec is roughly equivalent to a 1.9894 Hz cuttoff frequency
that was a quick chatgpt ask, it is not being used in this pull request anyways and wont be in any future ones as looking into the problem more showed this to be inaccurate

2024-09-16 20:55 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +                      time_constant=0.08,
it is not used in this pull request and wont be used when the relevant feature is presented for code review, in the future

2024-09-16 20:57 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +"""
I removed code that filtered and processed the data (other than the scaling) as it does pertain to this pull request

2024-09-16 20:58 UTC, ppolk-wave commented on dsp/graph_preprocessing.py
> +    # bipolar-transverse montage electrodes
I will look into this when I add additional montages as part of a future pull request. I believe the MyWave BPT montage order is different than what we use which is why I made my own

2024-09-16 20:59 UTC, ppolk-wave commented on graphs/eeg_viewer.py
> +                    color="black",
I changed to "#4E4E4E" so its visible in dark mode, thank you!

2024-09-16 21:11 UTC, ppolk-wave commented
I initially submitted a graph_processing.py file that had functions for features not yet worked on and not in this pull request. They have been removed and any feedback pertaining to this pull request should be implemented now.

2024-09-16 22:17 UTC, luis-wave approved these changes

2024-09-16 22:18 UTC, merged