Ppolk dods 106
luis-wave/wavelit pull request #54
Opened 2024-12-21 00:12 UTC by ppolk-wave

MWL HRV stats calculations added to the ECG page

2024-12-26 18:39 UTC, luis-wave reviewed
This PR, include too much from the original request. We only need to add it in the ECG tab and the updated heart rate calculation. MyWaveLab should not be included because it is a wrapper around mne. MyWaveAnalytics already handles the parsing, processing and storage of eeg/ecg data. 

MyWaveAnalytics already has a mw_object, if you want to access the raw MNE object you can do so with this line

raw = mw_object.eeg

From there you can use any other method outlined in MNE for eeg/ecg processing.

Take what you did in mywavelab/dsp/ecg_stats.py and store in somewhere in the DSP directory of wavelit if you want to extend heart rate calculation with your custom solution.

2024-12-27 23:13 UTC, luis-wave requested changes

2024-12-30 18:05 UTC, ppolk-wave commented on dsp/lab_ecg_stats.py
> +                ecg_data = calc_ecg_stats(
Can you please explain what you mean by this

2024-12-30 18:51 UTC, luis-wave commented on dsp/lab_ecg_stats.py
> +                ecg_data = calc_ecg_stats(
This comment is old.If we are not using linked ears or Cz to ref the ecg channel, it's not relevant

2024-12-30 18:57 UTC, merged